openapi: 3.0.1
info:
  title: RestAPIWithSecret
  description: API Definition of RestAPIWithSecret
  version: 1.0.0
servers:
- url: http://localhost:8290/restapiwithsecret
paths:
  /getsecret:
    get:
      responses:
        default:
          description: Default response
